### ISSUE TITLE
Create rule which allows to match the message against a configurable message format

### ISSUE THREAD

**Issue by hferentschik** [vbatts/git-validation#30]
I would like to have a rule which allows verifying a certain format of the first lines of the commit message. In the projects I am working we, for example, want to ensure that each commit message starts with the issue key the commit is related to, eg:

    JIRA-1001 Bla bla

I would like to do something like (using regexps):

    JIRA-[0-9]+ [A-Z].*

Looking at the current rules they are all static. What would be your idea around configurable rules?

**Comment by vbatts** [comment]
in the "first line" or matched at all in the message?

**Comment by hferentschik** [comment]
> in the "first line" or matched at all in the message?

In this particular case I am after verifying the first line, but I guess in a more generically it might make sense to be able to verify the message as a whole as well. Maybe this would be two different rules or just configurable via an option (whether to apply the rule to the first line or whole message).

**Comment by vbatts** [comment]
i'm thinking that the rules to run will just be able to accept a value. like `git-validation -run "dco,message_regexp='^JIRA-[0-9]+ [A-Z].*$'"`. This will take a little massaging, but should not break anyone's usage.

**Comment by hferentschik** [comment]
> i'm thinking that the rules to run will just be able to accept a value. like git-validation -run "dco,message_regexp='^JIRA-[0-9]+ [A-Z].*$'". 

Ok, so no config file or similar? What's about multiple arguments? So in your example - dco,message_regexp='^JIRA-[0-9]+ [A-Z].*$ - I guess _dco_ and message_regexp are the names of the rules to enable. The equals after _message_regexp_ is then a way to pass config values into the rule, in this case the regular exression. What if a rule would take more than one parameter? Is it up to the rule to handle the incoming value and potentially split it into multiple config values?

**Comment by vbatts** [comment]
in #31 i refactored a bit so that there could be multiple instances of valued rules like `.. -run "message_regexp='foo',message_regexp='bar'"`.
_dco_ is an existing rule being chosen to run as well.
If the rule needs multiple parameters, i suppose that would have to be parsed inside the rule itself, because it would get a string of the value

**Comment by hferentschik** [comment]
> If the rule needs multiple parameters, i suppose that would have to be parsed inside the rule itself, because it would get a string of the value

ok

**Comment by vbatts** [comment]
I've merged the feature now. You can `go get -u ...` and try it out!

**Comment by hferentschik** [comment]
Works like a charm. Thanks :-)

**Comment by vbatts** [comment]
yw!
