### ISSUE TITLE
handling for multiple path for exclude pathspec is required.

### ISSUE THREAD

**Issue by kunalkushwaha** [vbatts/git-validation#33]
For whitespace check currently, ``GIT_CHECK_EXCLUDE`` Environment variable is considered. This variable internally build the command part as `` -- . ":(exclude)$(GIT_CHECK_EXCLUDE)"``

This is problem, if multiple folders are required to excluded.

I am facing this issue with https://github.com/containerd/containerd/pull/2178/files#diff-481f5b73de80d96d8634d17ba488d170R27, where apart from `vendor`, additional folder `scripts/validate/template` is also required to be skipped. 

Finally I got the expected output from git  command 
```
git --no-pager log --check 12725bf3094871f0cad5909f2db18b824d5d1ff2^..12725bf3094871f0cad5909f2db18b824d5d1ff2    -- . ":(exclude)./vendor" -- . ":(exclude)./script/validate/template"
```
where multiple ``:(exclude)`` is required.

**Comment by kunalkushwaha** [comment]
Though a dirty hack also works 
```
GIT_CHECK_EXCLUDE="./vendor\" -- . :(exclude)\"./script/validate/template" git-validation -q -run DCO,short-subject,dangling-whitespace
```

**Comment by vbatts** [comment]
so:
```shell
GIT_CHECK_EXCLUDE="./vendor:./script/validate/template" \
git-validation \
-q \
-run DCO,short-subject,dangling-whitespace
```

**Comment by vbatts** [comment]
LGTM
