### ISSUE TITLE
Fails noisily on an empty commit range

### ISSUE THREAD

**Issue by mtrmac** [vbatts/git-validation#36]
```console
$ git-validation -range HEAD..HEAD
fatal: ambiguous argument '': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
ERRO[0000] [git] cmd: "git --no-pager log -1 --pretty=format:%t " 
2018/08/27 16:10:30 exit status 128
```

This seems to happen because https://github.com/vbatts/git-validation/blob/656ba47bb0be8aba4934bb4b2e91863edb406c36/git/commits.go#L25 makes `commitHashes` a `[]string{""}` instead of an empty array.

(This shows up after https://github.com/containers/image/pull/498 when there are no commits on top of upstream’s master branch.)

**Comment by vbatts** [comment]
@mtrmac are you working on a fix for this presently?

**Comment by mtrmac** [comment]
Not right now. Eventually the errors will probably motivate me to prepare a PR, but not today :)

**Comment by giuseppe** [comment]
I saw this one too.  Prepared a PR here: https://github.com/vbatts/git-validation/pull/41
