### ISSUE TITLE
binary availability

### ISSUE THREAD

**Issue by baude** [vbatts/git-validation#44]
we are using git-validation on almost all containers/<project>s.  not all of the projects are go-based. adding golang to their stacks to build git-validation is fairly heavy weight.  it would be nice to have a 'latest' binary being built at each merge so we could curl it and skip the whole build part.

@vbatts wdyt? something you'd work with us on?

**Comment by vbatts** [comment]
Oh fair. I should coordinate that with releases.

-------- Original Message --------

**Comment by vbatts** [comment]
https://github.com/vbatts/git-validation/releases/tag/v1.0.0

**Comment by vbatts** [comment]
and i just tagged another from master
https://github.com/vbatts/git-validation/releases/tag/v1.1.0
