### ISSUE TITLE
git rev-list bug

### ISSUE THREAD

**Issue by lengrongfu** [vbatts/git-validation#53]
This is the result of GitHub workflow execution.
![image](https://user-images.githubusercontent.com/15009201/130648539-1be81319-4260-4e13-a3f6-c3c0147a3a7a.png)

This is the result of my local execution.
![image](https://user-images.githubusercontent.com/15009201/130648849-de82c5d7-6702-46cf-a500-f1904460a062.png)

**Comment by lengrongfu** [comment]
https://stackoverflow.com/questions/63284060/git-rev-list-not-working-inside-github-action

**Comment by vbatts** [comment]
@lengrongfu thanks for the report! 
what's `cat /etc/os-release` and `git --version` of your local system?

**Comment by vbatts** [comment]
and guessing from the image, the repo you're working from is
distribution/distribution?

**Comment by lengrongfu** [comment]
> @lengrongfu thanks for the report!
> what's `cat /etc/os-release` and `git --version` of your local system?

`git --version`: git version 2.30.1 (Apple Git-130)
`os system`: Mac 11.3.1

**Comment by lengrongfu** [comment]
> and guessing from the image, the repo you're working from is distribution/distribution?

yes

**Comment by lengrongfu** [comment]
Would you like to help me look at this problem?
https://github.com/lengrongfu/distribution/runs/3413200873?check_suite_focus=true

**Comment by vbatts** [comment]
It's odd that it just began failing.
It doesn't look like the workflow config related to this changed.
I wonder if the actual @checkout workflow stopped fetching the depth?

**Comment by lengrongfu** [comment]
![image](https://user-images.githubusercontent.com/15009201/130662497-21b6626a-6f3e-46d7-99e8-01431982b241.png)

**Comment by lengrongfu** [comment]
I was thinking, is it because my git submission is not standardized, which causes it to run wrong? Can you describe what is the main purpose of using the git rev-list command for verification?

**Comment by vbatts** [comment]
the purpose of the `rev-list` is to collect what commits are in the
range to be checked. 

I think this will need to be rethought, if Github Actions are pruning
the depth. Perhaps there is an environment variable that indicates which
commits are even present in the cloned repo?
