### ISSUE TITLE
New release of git-validation

### ISSUE THREAD

**Issue by ginglis13** [vbatts/git-validation#57]
Hi there, thanks for providing this tool. My team uses this in a few of our open source projects :) 

Recently we ran into the issue resolved by this commit https://github.com/vbatts/git-validation/commit/fd9b8fa61232acd41f44cdf76b11fa0059c8aef2 to fix CRLF parsing in commit messages. We've addressed this for now by installing git-validation @ `master`, but would prefer to have a pinned release with the fix. Is there any newer release planned for the tool?

**Comment by vbatts** [comment]
Will do!

**Comment by vbatts** [comment]
https://github.com/vbatts/git-validation/releases/tag/v1.2.0
